platform :ios, '14.0'
source 'https://github.com/euronovate/euronovate-pods.git'
source 'https://cdn.cocoapods.org/'

target 'MultiLayout' do
  use_frameworks!
  pod 'ENDigitalSignage', '1.3.9'
  pod 'ENPDFMiddleware', '1.3.9'
  pod 'ENViewer', '1.3.9'
  pod 'ENSignatureBox', '1.3.9'
  pod 'ENBioLibrary', '1.3.9'  
end

# Xcode 14.3 breaks pods with deployment target below iOS 11
# https://developer.apple.com/forums/thread/728021
# https://stackoverflow.com/a/75729977/2699091
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      if target.name == 'AnyCodable-FlightSchool' ||
         target.name == 'BlueCryptor' ||
         target.name == 'BlueRSA' ||
         target.name == 'KituraContracts' ||
         target.name == 'LoggerAPI' ||
         target.name == 'Logging' ||
         target.name == 'ReachabilitySwift' ||
         target.name == 'SwiftKeychainWrapper' ||
         target.name == 'SwiftSignalRClient' ||
         target.name == 'XMLCoder'
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
      end

      # Assicura che BUILD_LIBRARY_FOR_DISTRIBUTION sia sempre configurato correttamente.
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
end