source 'https://github.com/euronovate/euronovate-pods.git'
source 'https://cdn.cocoapods.org/'

target 'DSPubSubSoftServerSignature' do

  use_frameworks!
  pod 'ENDigitalSignage', '1.3.5'
  pod 'ENPubSub', '1.3.5'
  pod 'ENSoftServer', '1.3.5'
  pod 'ENSignatureBox', '1.3.5'
  pod 'ENViewer', '1.3.5'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
