source 'https://github.com/euronovate/euronovate-pods.git'
source 'https://cdn.cocoapods.org/'

target 'DSPubSubSoftServerSignature' do

  use_frameworks!
  pod 'ENDigitalSignage'
  pod 'ENPubSub'
  pod 'ENSoftServer'
  pod 'ENSignatureBox'
  pod 'ENViewer'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
